name: todo_app
description: The classic TODO app for modularization studies.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  bloc_test: ^9.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_lints: ^2.0.0
  fake_async: ^1.3.1

flutter:

  uses-material-design: true
